# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown

# PROD - Site settings
# title: Letícia Capelão
# email: contato@leticiacapelao.com
# description: > # this means to ignore newlines until "baseurl:"
#   Mapas pessoais dos Anjos da Guarda, consultas ao Tarot dos Anjos,
#   Tarot das Almas Gêmeas, análise da numerologia cabalística, associação da terapia de aromas,
#   pedras e minerais, cores e músicas aos Anjos da Guarda.

#   Gestão e desenvolvimento de cursos a distância, técnicas e ferramentas para contribuir
#   para a acessibilidade dos surdos na educação a distância e na web, avaliação de qualidade 
#   de uso de sistemas (acessibilidade, usabilidade, comunicabilidade) pautados na abordagem da 
#   Interação Humano-Computador e Engenharia Semiótica.

#   Sou brasileira e mineira, com dupla nacionalidade, também portuguesa. Amante da natureza, 
#   das flores, da liberdade e protetora de animais. Gosto de dança, música, esportes, comidas 
#   naturais, livros e outras maravilhas que a vida oferece. A alegria do meu nome! Sou ouvinte 
#   e tenho um irmão surdo. O que me levou a atuar na área de Libras e acessibilidade para surdos.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://www.leticiacapelao.com" # the base hostname & protocol for your site

# DEV - Site settings
title: Letícia Capelão
email: contato@leticiacapelao.com
description: > # this means to ignore newlines until "baseurl:"
 Mapas pessoais dos Anjos da Guarda, consultas ao Tarot dos Anjos,
  Tarot das Almas Gêmeas, análise da numerologia cabalística, associação da terapia de aromas,
  pedras e minerais, cores e músicas aos Anjos da Guarda.

  Gestão e desenvolvimento de cursos a distância, técnicas e ferramentas para contribuir
  para a acessibilidade dos surdos na educação a distância e na web, avaliação de qualidade 
  de uso de sistemas (acessibilidade, usabilidade, comunicabilidade) pautados na abordagem da 
  Interação Humano-Computador e Engenharia Semiótica.

  Sou brasileira e mineira, com dupla nacionalidade, também portuguesa. Amante da natureza, 
  das flores, da liberdade e protetora de animais. Gosto de dança, música, esportes, comidas 
  naturais, livros e outras maravilhas que a vida oferece. A alegria do meu nome! Sou ouvinte 
  e tenho um irmão surdo. O que me levou a atuar na área de Libras e acessibilidade para surdos.
baseurl: "/leticiacapelao" # the subpath of your site, e.g. /blog
url: "http://cafe-do.github.io" # the base hostname & protocol for your site
